### ISSUE TITLE
pg. 13 swapped 

### ISSUE THREAD

**Issue by CBtiger** [onekk/freecad-doc#12]
I think the two tab names should be swapped.

Text from page  13, english version v0.56
An **Object** component that contains an object’s data used by the “modeling en-
gine” that is shown in property editor in the **View** tab.
A **ViewObject** component that contains view data, used by the “graphics engine”,
for example color and transparency; This component is shown in the property
editor in the **Data** tab.

on pg. 15
"Surfaces for example a **piano**," -> "Surfaces for example a **plane**," ?

**Comment by onekk** [comment]
Thanks.

Probably yes, I note this and check in the revision I'm preparing.

If you note sone other problems even point not clear  please let me know and I will amend the text.
