### ISSUE TITLE
Mr Pieterse, 

### ISSUE THREAD

**Issue by PeterPieterse** [onekk/freecad-doc#13]
I've downloaded Freecad sucessfully, however as the app finishes installing it closes immediately.
Trouble shooting cannot solve the problem, the suggestion is "Incompatability"
Any suggested solution will be welcomed.

**Comment by onekk** [comment]
This is the Issue tracker for my personal freecad-doc folder only.

Here we will discuss only of error or extension for the document I have created.

For a general help better to go to: https://forum.freecad.org for any other helps.
