### ISSUE TITLE
Feedback: make hyperlinks clickable

### ISSUE THREAD

**Issue by luzpaz** [onekk/freecad-doc#2]
Not all hyperlink mentioned in the document are active/clickable. 

![image](https://user-images.githubusercontent.com/4140247/147988022-eecbad99-c78c-4c13-938c-b417f2d37668.png)

**Comment by onekk** [comment]
Hello, you are referring to the English version" of this guide?

**Comment by luzpaz** [comment]
Yes, but I think I saw this in the original version too

**Comment by onekk** [comment]
Many thanks.

I have sent you a PM, if I've guessed right who you are.
