### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by luzpaz** [onekk/freecad-doc#3]
![image](https://user-images.githubusercontent.com/4140247/147988259-aeed1bb4-dcf7-4a96-aa65-58e763035c28.png)
![image](https://user-images.githubusercontent.com/4140247/147988326-2b940946-dc45-4e50-b8e0-78c422e2e245.png)

**Comment by onekk** [comment]
Thank, these are some Hardcoded headers, I have found some of them in the meantime, but not all.
