### ISSUE TITLE
Feature: Can we make something similiar to the OpenSCAD cheatsheet?

### ISSUE THREAD

**Issue by luzpaz** [onekk/freecad-doc#5]
https://openscad.org/cheatsheet/ but FreeCAD ? :smile:

**Comment by onekk** [comment]
Yes and no, I have to investigate something about nesting "frames" to be able to compose such a cheatsheet.

So I think it would be a "goal for future", first thing, is to finish "English translation", then some improvements could be made.

It depends also on how many users will appreciate this guide, as I'm using a professional Typesetter program is not like "writing a Word document", so some thing have to be tested and "coded".
