### ISSUE TITLE
Please provide some insight

### ISSUE THREAD

**Issue by r-d-r-d** [onekk/freecad-doc#7]
I saw you on the FreeCAD discussion forum. I am new to this. My project requires me to automate running of a macro. Is it possible to convert a .FCMacro to .exe file so that I can run the macro script without opening freeCAD

**Comment by onekk** [comment]
No it is not possible. I have explained in the forum why. For short, FC is too complex to be shrinked in a "single file executable".

Regards

Carlo D.
