### ISSUE TITLE
PDF Problem

### ISSUE THREAD

**Issue by falviani** [onekk/freecad-doc#9]
Hi,

I downloaded your english PDF document and am unable to open it with any application on my Windows 10 machine. All applications I have tried report the file is corrupted.

-Frank Alviani
(frank.alviani@gmail.com)

**Comment by onekk** [comment]
Strange enough it opens in GitHub and in Linux without problems.

I have no way to test it in Windows, as my machine has only old win7 installation, a no win10.

let me check pdf file version.

**Comment by onekk** [comment]
Try now with the new file dated today, I have modified the pdf generation to put a proper title and author in the pdf infos.

Checked with a pdf validator and it seems OK.
